<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_help().
 */
function custom_spotify_app_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.custom_spotify_app':
      return '<p>' . t('This module integrates with the Spotify API to display artist information on a custom block and a page.') . '</p>';
      break;
  }
}
