<?php

namespace Drupal\custom_spotify_app;

use Drupal\Core\Extension\ModuleHandlerInterface;
use Drupal\Core\StringTranslation\StringTranslationTrait;

/**
 * Implements hook_install().
 */
function custom_spotify_app_install() {

  // Enable the pathauto, admin_toolbar and admin_toolbar_tools module.

  \Drupal::service('module_installer')->install(['admin_toolbar']);
  \Drupal::service('module_installer')->install(['admin_toolbar_tools']);

}
