spotify_api_settings:
  type: config_object
  label: 'Spotify API Settings'
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
    cache_time:
      type: integer
      label: 'Cache Time'

