custom_spotify_app.settings:
  type: config_object
  label: 'Drupal Challenge Spotify Settings'
  mapping:
    access_token:
      type: string
      label: 'Spotify Access Token'
    client_id:
      type: string
      label: 'Spotify Client ID'
    client_secret:
      type: string
      label: 'Spotify Client Secret'
    spotify_access_token_created_at:
      type: date_format
      label: 'Spotify Access Token Created At'
    spotify_access_token_expiration_time:
      type: integer
      label: 'Spotify Access Token Expiration Time'
