custom_spotify_app.settings:
  type: config_object
  label: 'Drupal Challenge Spotify Settings'
  mapping:
    spotify_access_token:
      type: string
      label: 'Spotify Access Token'
    spotify_client_id:
      type: string
      label: 'Spotify Client ID'
    spotify_client_secret:
      type: string
      label: 'Spotify Client Secret'
    spotify_access_token_created_at:
      type: date_format
      label: 'Spotify Access Token Created At'
    spotify_access_token_expiration_time:
      type: integer
      label: 'Spotify Access Token Expiration Time'
    spotify_api_query_limit:
      type: integer
      label: 'Spotify API Query Limit'
    spotify_api_query_offset:
      type: integer
      label: 'Spotify API Query Offset'
